(defpackage :day02
  (:use :cl :arrows)
  (:import-from :trivia #:match)
  (:import-from :ppcre #:scan)
  (:export #:main))

(in-package :day02)

(defun part01 (content)
  (labels ((parse (line)
             (let* ((lr (str:split "-" line))
                    (l (parse-integer (first lr)))
                    (r (parse-integer (second lr))))
               (list l r)))
           (expand (lr)
             (loop for i from (first lr) to (second lr) collect i))
           (is-invalid? (id)
             (scan "^(.+)(\\1)$" (write-to-string id))))
    (-<> (str:split "," content)
         (map 'list #'parse <>)
         (map 'list #'expand <>)
         (apply #'append <>)
         (remove-if-not #'is-invalid? <>)
         (apply #'+ <>))))

(defun part02 (content)
  (labels ((parse (line)
             (let* ((lr (str:split "-" line))
                    (l (parse-integer (first lr)))
                    (r (parse-integer (second lr))))
               (list l r)))
           (expand (lr)
             (loop for i from (first lr) to (second lr) collect i))
           (is-invalid? (id)
             (scan "^(.+)(\\1)+$" (write-to-string id))))
    (-<> (str:split "," content)
         (map 'list #'parse <>)
         (map 'list #'expand <>)
         (apply #'append <>)
         (remove-if-not #'is-invalid? <>)
         (apply #'+ <>))))

(defun main ()
  (let ((content (utils:read-input "02")))
    (format t "~A~%" (part01 content))
    (format t "~A~%" (part02 content))))
